global:
  storageClass: longhorn
  imageRegistry: registry.openmoodle.local
moodle:
  replicaCount: 3
  image: { repository: openmoodle/moodle-app, tag: "4.4.0", pullPolicy: IfNotPresent }
  nginx: { repository: openmoodle/moodle-nginx, tag: "4.4.0", pullPolicy: IfNotPresent }
  resources:
    requests: { cpu: 500m, memory: 1Gi }
    limits: { cpu: 2000m, memory: 4Gi }
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
database: { host: "", name: moodle, user: moodle }
secrets:
  existingSecret: ""
  create: false
  databasePassword: ""
  adminPassword: ""
  minioAccessKey: ""
  minioSecretKey: ""
redis: { enabled: true, host: "" }
mariadb: { enabled: true }
minio: { enabled: true }
moodledata: { size: 100Gi, accessMode: ReadWriteMany }
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: moodle.openmoodle.local
      paths: [{ path: /, pathType: Prefix }]
  tls: []
  annotations: {}
cron: { enabled: true, schedule: "*/5 * * * *" }
varnish: { enabled: false, replicaCount: 2, cacheSize: 2G }
monitoring:
  enabled: true
  serviceMonitor: { enabled: false, interval: 30s }
networkPolicy:
  enabled: true
  ingressNamespaceSelector:
    kubernetes.io/metadata.name: ingress-nginx