version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/tofu"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/helm/openmoodle"
    schedule:
      interval: "weekly"
