apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openmoodle.fullname" . }}
  labels: {{- include "openmoodle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.moodle.replicaCount }}
  selector:
    matchLabels:
      {{- include "openmoodle.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openmoodle.labels" . | nindent 8 }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.podManagement.terminationGracePeriodSeconds | default 60 }}
      securityContext:
        seccompProfile: { type: RuntimeDefault }
        fsGroup: 33
      {{- if .Values.moodle.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.moodle.imagePullSecrets | nindent 8 }}
      {{- end }}
      initContainers:
{{- include "openmoodle.initContainers" . | nindent 6 }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "openmoodle.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: {{ include "openmoodle.name" . }}
                    app.kubernetes.io/instance: {{ .Release.Name }}
      containers:
{{- include "openmoodle.appContainer" . | nindent 6 }}
{{- include "openmoodle.webContainer" . | nindent 6 }}
{{- if .Values.monitoring.enabled }}
        - name: nginx-exporter
          image: "nginx/nginx-prometheus-exporter:1.1.0"
          imagePullPolicy: IfNotPresent
          args:
            - -nginx.scrape-uri
            - http://localhost:8080/stub_status
          ports: [{ name: metrics, containerPort: 9113 }]
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            allowPrivilegeEscalation: false
            capabilities: { drop: [ALL] }
            readOnlyRootFilesystem: true
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { cpu: 200m, memory: 128Mi }
{{- end }}
      volumes:
        - name: moodledata
          persistentVolumeClaim: { claimName: {{ include "openmoodle.fullname" . }}-moodledata }
        - name: config
          configMap: { name: {{ include("openmoodle.fullname", .) }}-config }
          readOnly: true
        - name: tmp
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}