{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openmoodle.fullname" . }}
  annotations:
    {{- if .Values.ingress.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.issuerName }}
    {{- end }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend: { service: { name: {{ include "openmoodle.fullname" $ }}, port: { number: 80 } } }
          {{- end }}
    {{- end }}
  {{- if not .Values.ingress.tls }}
  {{- fail "ingress.tls must be configured when ingress.enabled is true" }}
  {{- else }}
  tls: {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- if and .Values.ingress.enabled .Values.ingress.certManager.enabled .Values.ingress.tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "openmoodle.fullname" . }}-tls
spec:
  secretName: {{ (index .Values.ingress.tls 0).secretName }}
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}
  issuerRef:
    name: {{ .Values.ingress.certManager.issuerName }}
    kind: {{ .Values.ingress.certManager.issuerKind | default "ClusterIssuer" }}
{{- end }}
