{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "openmoodle.fullname" . }}
  labels: {{- include "openmoodle.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "openmoodle.labels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - ports:
        - { protocol: TCP, port: 8080 }
      from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 14 }}
  egress:
    - ports:
        - { protocol: TCP, port: 53 }
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 5432 }
        - { protocol: TCP, port: 6379 }
        - { protocol: TCP, port: 443 }
    {{- if .Values.fileStorage.enabled }}
    - to:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.s3Cidr | default "52.216.0.0/15" }}
      ports:
        - { protocol: TCP, port: 443 }
    {{- end }}
    {{- if and .Values.backup.enabled .Values.backup.minio.enabled }}
    - to:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.s3Cidr | default "52.216.0.0/15" }}
      ports:
        - { protocol: TCP, port: 443 }
    {{- end }}
{{- end }}
