{{- if .Values.secrets.create }}
{{- if .Values.redis.auth.enabled }}
{{- if not .Values.secrets.redisPassword }}
{{ fail "secrets.redisPassword is required when secrets.create is true and redis auth is enabled" }}
{{- end }}
{{- end }}
{{- if .Values.backup.encryption.enabled }}
{{- if not .Values.secrets.backupEncryptionKey }}
{{ fail "secrets.backupEncryptionKey is required when backup.encryption.enabled is true" }}
{{- end }}
{{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include("openmoodle.fullname") . }}-secrets
  labels:
    {{- include "openmoodle.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.redis.auth.enabled }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
  {{- end }}
  {{- if .Values.fileStorage.enabled }}
  s3-access-key: {{ .Values.fileStorage.s3.accessKey | quote }}
  s3-secret-key: {{ .Values.fileStorage.s3.secretKey | quote }}
  {{- end }}
  {{- if .Values.backup.encryption.enabled }}
  backup-encryption-key: {{ .Values.secrets.backupEncryptionKey | quote }}
  {{- end }}
{{- end }}
