{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "openmoodle.fullname" . }}
  labels: {{- include "openmoodle.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "openmoodle.labels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}